### ISSUE TITLE
Question: Python 3.7 support?

### ISSUE THREAD

**Issue by tmaniac** [caronc/pynzbget#9]
I love the scripts you create;

Will there be any python 3.x support for your scripts/framework?

thanks

**Comment by caronc** [comment]
Not sure what the effort level involved is, but i'll add it to the TODO list. :slightly_smiling_face:

**Comment by caronc** [comment]
Sorry it took so long; but I think I have a [working Python 3 branch](https://github.com/caronc/pynzbget/tree/python3-support) of this script (compatible with both Python 2 and 3).

**Comment by caronc** [comment]
Going to close this ticket off now that all the changes are merged.  If you have any issues or concerns; feel free to comment on this ticket or open another! :slightly_smiling_face:
